name: darwin
version: 0.1.1
description: Genetic algorithm library for Dart.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/darwin
#dependencies:
dev_dependencies:
  unittest: any
