name: darwin
version: 0.4.1
description: >
  A genetic/evolutionary algorithm library for Dart. Given a population
  of phenotypes, an evaluator (fitness function), and time, the algorithm
  will evolve the population until it crosses given fitness threshold.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/darwin

environment:
  sdk: ">=1.24.0 <3.0.0"

dependencies:
  meta: ^1.1.6
dev_dependencies:
  test: '>=0.12.30 <2.0.0'
